FROM node:14.15.3-alpine3.10

# set working directory
RUN mkdir /app
WORKDIR /app

# install app dependencies
COPY package*.json ./
COPY ./src ./src
EXPOSE 5000
ENV PATH /src/node_modules/.bin:$PATH
RUN npm install

# start app

CMD ["npm", "run","dev"]