FROM node:14.15.3-alpine3.10

# set working directory
RUN mkdir /app
WORKDIR /app

# install app dependencies
COPY package*.json ./
RUN npm install

COPY . ./

RUN npm run build
EXPOSE 3000

# start app

CMD ["npm", "run","dev"]