FROM node:14.15.3-alpine3.10

# set working directory
RUN mkdir /app
WORKDIR /app

# install app dependencies
COPY package*.json ./
RUN npm install

COPY . ./

EXPOSE 3000
RUN npm run build

# start app

CMD ["npm", "run","dev"]